<?php
/**
 * Llms.txt generator: serves a machine-readable Markdown summary of the site
 * at /llms.txt, following the llmstxt.org standard so LLMs can understand
 * the site's structure and content.
 *
 * @see     https://llmstxt.org
 * @package Beplus_Metadata_AI_Analyzer
 */

if ( ! defined( 'ABSPATH' ) ) {
	exit;
}

/**
 * Class SSO_Llms_Txt
 */
class SSO_Llms_Txt {

	/**
	 * Singleton instance.
	 *
	 * @var SSO_Llms_Txt|null
	 */
	private static $instance = null;

	/**
	 * Get the singleton instance.
	 *
	 * @return SSO_Llms_Txt
	 */
	public static function instance() {
		if ( null === self::$instance ) {
			self::$instance = new self();
		}
		return self::$instance;
	}

	/**
	 * Constructor.
	 */
	private function __construct() {
		add_action( 'init', array( $this, 'add_rewrite_rule' ) );
		add_filter( 'query_vars', array( $this, 'add_query_var' ) );
		add_action( 'template_redirect', array( $this, 'serve_llms_txt' ) );
	}

	/**
	 * Register the /llms.txt rewrite rule.
	 */
	public function add_rewrite_rule() {
		add_rewrite_rule( '^llms\.txt$', 'index.php?sso_llms_txt=1', 'top' );
	}

	/**
	 * Expose the custom query var to WordPress.
	 *
	 * @param string[] $vars Existing query vars.
	 * @return string[]
	 */
	public function add_query_var( $vars ) {
		$vars[] = 'sso_llms_txt';
		return $vars;
	}

	/**
	 * Serve the llms.txt file when the rewrite rule is triggered.
	 */
	public function serve_llms_txt() {
		if ( ! get_query_var( 'sso_llms_txt' ) ) {
			return;
		}

		// Only serve when the feature is enabled in Settings.
		if ( ! SSO_Settings::get( 'advanced', 'llms_txt_enabled', 0 ) ) {
			status_header( 404 );
			exit;
		}

		$content = $this->generate_content();

		header( 'Content-Type: text/plain; charset=utf-8' );
		header( 'X-Robots-Tag: noindex' );
		header( 'Cache-Control: public, max-age=3600' );

		echo $content; // phpcs:ignore WordPress.Security.EscapeOutput.OutputNotEscaped -- Plain-text file, not HTML; every dynamic value is sanitised in generate_content().
		exit;
	}

	/**
	 * Build the full llms.txt content string.
	 *
	 * @return string
	 */
	public function generate_content() {
		$site_name = get_bloginfo( 'name' );
		$site_desc = get_bloginfo( 'description' );
		$site_url  = home_url();
		$language  = get_bloginfo( 'language' );

		$lines = array();

		// --- Header ---
		$lines[] = '# ' . $site_name;
		$lines[] = '';
		if ( $site_desc ) {
			$lines[] = '> ' . $site_desc;
			$lines[] = '';
		}

		// --- About ---
		$lines[] = '## About';
		$lines[] = 'Site URL: ' . $site_url;
		$lines[] = 'Language: ' . $language;
		$lines[] = 'Generated: ' . gmdate( 'Y-m-d' );
		$lines[] = '';

		// --- Recent Posts ---
		$lines[] = '## Recent Posts';
		$posts   = get_posts(
			array(
				'numberposts' => 20,
				'post_status' => 'publish',
				'orderby'     => 'date',
				'order'       => 'DESC',
			)
		);
		foreach ( $posts as $post ) {
			$meta_desc = get_post_meta( $post->ID, '_sso_meta_description', true );
			$desc      = $meta_desc ? $meta_desc : wp_trim_words( wp_strip_all_tags( $post->post_content ), 20, '...' );
			$desc      = str_replace( array( "\r", "\n" ), ' ', $desc );
			$lines[]   = sprintf( '- [%s](%s): %s', $post->post_title, get_permalink( $post ), $desc );
		}
		$lines[] = '';

		// --- Pages ---
		$lines[] = '## Pages';
		$pages   = get_pages(
			array(
				'sort_column' => 'menu_order',
				'post_status' => 'publish',
			)
		);
		foreach ( $pages as $page ) {
			$meta_desc = get_post_meta( $page->ID, '_sso_meta_description', true );
			if ( $meta_desc ) {
				$lines[] = sprintf( '- [%s](%s): %s', $page->post_title, get_permalink( $page ), $meta_desc );
			} else {
				$lines[] = sprintf( '- [%s](%s)', $page->post_title, get_permalink( $page ) );
			}
		}
		$lines[] = '';

		// --- Categories (top-level) ---
		$categories = get_categories(
			array(
				'hide_empty' => true,
				'parent'     => 0,
				'number'     => 20,
			)
		);
		if ( $categories && ! is_wp_error( $categories ) ) {
			$lines[] = '## Categories';
			foreach ( $categories as $cat ) {
				$lines[] = sprintf( '- [%s](%s): %d posts', $cat->name, get_category_link( $cat->term_id ), $cat->count );
			}
			$lines[] = '';
		}

		// --- Sitemap reference ---
		$lines[] = '## Sitemap';
		$lines[] = 'XML Sitemap: ' . home_url( '/sitemap.xml' );
		$lines[] = '';

		// --- Optional custom content from Settings ---
		$custom = get_option( 'sso_llms_custom_content', '' );
		if ( $custom ) {
			$lines[] = '## Additional Information';
			$lines[] = sanitize_textarea_field( $custom );
			$lines[] = '';
		}

		$lines[] = '---';
		$lines[] = 'Generated by Beplus Metadata AI Analyzer';

		return implode( "\n", $lines );
	}

	/**
	 * Flush rewrite rules so the /llms.txt endpoint is immediately accessible.
	 * Called on plugin activation and when the llms.txt setting is saved.
	 */
	public function flush_rewrite() {
		$this->add_rewrite_rule();
		flush_rewrite_rules();
	}
}
